<?php include('hnav.php'); ?>


<div class="site-blocks-cover inner-page-cover overlay" style="background-image: url(images/banner2.png);" data-aos="fade" data-stellar-background-ratio="0.5">
    <div class="container">
        <div class="row align-items-center justify-content-center text-center">

            <div class="col-md-10" data-aos="fade-up" data-aos-delay="400">


                <div class="row justify-content-center mt-5">
                    <div class="col-md-8 text-center">
                        <h1>Many People Selling Online</h1>
                        <p class="mb-0">April 24th, 2019 <span class="mx-2">&bullet;</span> by <a href="#" class="text-white">Colorlib</a></p>
                    </div>
                </div>


            </div>
        </div>
    </div>
</div>

<div class="site-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">

                <figure>
                    <img src="images/tailor.png" alt="Image" class="img-fluid">
                    <figcaption>This is an image</figcaption>
                </figure>

                <p>Our mission ultimately is GETTING THERE BY LEAVING HERE. There, being God’s peak of possibility for our individual and corporate entities and Here, our current, present state of status in all ramifications of life. Our vision is effectively EMPHASIZING THE REALITY OF PURPOSE IN THE GENUINENESS OF CREATION. <br>We have bet our lives on one thing; PURPOSE! We have made a vow on fulfilment. We’ll not bow to compromise – the killer of destiny.</p>
                <p>We comprise of sisters and brothers whose hearts have been regenerated by the Word and Blood of Redemption in Christ Jesus. Those who mind heavenly things and seek first and always, the Kingdom’s mandate!<br>
                    You can join us simply and truly with a deep convincing proof on integrity, commitment to serving the Lord and real spiritual and moral character development garnished with maturity.</p>


                <div class="pt-5">
                    <p>Categories: <a href="#">Food</a>, <a href="#">Travel</a> Tags: <a href="#">#manila</a>, <a href="#">#asia</a></p>
                </div>


                <div class="pt-5">
                    <h3 class="mb-5">6 Comments</h3>
                    <ul class="comment-list">
                        <li class="comment">
                            <div class="vcard">
                                <img src="images/person_1.jpg" alt="Image placeholder">
                            </div>
                            <div class="comment-body">
                                <h3>Jean Doe</h3>
                                <div class="meta">January 9, 2018 at 2:21pm</div>
                                <p>Footpaths was birthed out of hunger for The Truth. Our time and world is laced with falsehood and distortion which goes round like a wildfire especially on our social media. It is intended to be an highly-engaging Christ-centered brand of choice, providing excellent quality of content, with purposeful impact on readers coupled with rare breeds of columnists!</p>
                                <p><a href="#" class="reply rounded">Reply</a></p>
                            </div>
                        </li>

                        <li class="comment">
                            <div class="vcard">
                                <img src="images/person_1.jpg" alt="Image placeholder">
                            </div>
                            <div class="comment-body">
                                <h3>Jean Doe</h3>
                                <div class="meta">January 9, 2018 at 2:21pm</div>
                                <p> We are conscious not to forget, that abuse is inevitable when purpose is lost to the dust of ignorance. ... emphasizing the reality of purpose in the genuineness of creation</p>
                                <p><a href="#" class="reply rounded">Reply</a></p>
                            </div>

                            <ul class="children">
                                <li class="comment">
                                    <div class="vcard">
                                        <img src="images/person_1.jpg" alt="Image placeholder">
                                    </div>
                                    <div class="comment-body">
                                        <h3>Jean Doe</h3>
                                        <div class="meta">January 9, 2018 at 2:21pm</div>
                                        <p> We are conscious not to forget, that abuse is inevitable when purpose is lost to the dust of ignorance.</p>
                                        <p><a href="#" class="reply rounded">Reply</a></p>
                                    </div>


                                    <ul class="children">
                                        <li class="comment">
                                            <div class="vcard">
                                                <img src="images/person_1.jpg" alt="Image placeholder">
                                            </div>
                                            <div class="comment-body">
                                                <h3>Jean Doe</h3>
                                                <div class="meta">January 9, 2018 at 2:21pm</div>
                                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur quidem laborum necessitatibus, ipsam impedit vitae autem, eum officia, fugiat saepe enim sapiente iste iure! Quam voluptas earum impedit necessitatibus, nihil?</p>
                                                <p><a href="#" class="reply rounded">Reply</a></p>
                                            </div>

                                            <ul class="children">
                                                <li class="comment">
                                                    <div class="vcard">
                                                        <img src="images/person_1.jpg" alt="Image placeholder">
                                                    </div>
                                                    <div class="comment-body">
                                                        <h3>Jean Doe</h3>
                                                        <div class="meta">January 9, 2018 at 2:21pm</div>
                                                        <p>Footpaths was birthed out of hunger for The Truth. Our time and world is laced with falsehood and distortion which goes round like a wildfire especially on our social media. It is intended to be an highly-engaging Christ-centered brand of choice, providing excellent quality of content, with purposeful impact on readers coupled with rare breeds of columnists!</p>
                                                        <p><a href="#" class="reply rounded">Reply</a></p>
                                                    </div>
                                                </li>
                                            </ul>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                        </li>

                        <li class="comment">
                            <div class="vcard">
                                <img src="images/person_1.jpg" alt="Image placeholder">
                            </div>
                            <div class="comment-body">
                                <h3>Jean Doe</h3>
                                <div class="meta">January 9, 2018 at 2:21pm</div>
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur quidem laborum necessitatibus, ipsam impedit vitae autem, eum officia, fugiat saepe enim sapiente iste iure! Quam voluptas earum impedit necessitatibus, nihil?</p>
                                <p><a href="#" class="reply rounded">Reply</a></p>
                            </div>
                        </li>
                    </ul>
                    <!-- END comment-list -->

                    <div class="comment-form-wrap pt-5">
                        <h3 class="mb-5">Leave a comment</h3>
                        <form action="#" class="p-5 bg-light">
                            <div class="form-group">
                                <label for="name">Name *</label>
                                <input type="text" class="form-control" id="name">
                            </div>
                            <div class="form-group">
                                <label for="email">Email *</label>
                                <input type="email" class="form-control" id="email">
                            </div>
                            <div class="form-group">
                                <label for="website">Website</label>
                                <input type="url" class="form-control" id="website">
                            </div>

                            <div class="form-group">
                                <label for="message">Message</label>
                                <textarea name="" id="message" cols="30" rows="10" class="form-control"></textarea>
                            </div>
                            <div class="form-group">
                                <input type="submit" value="Post Comment" class="btn btn-primary">
                            </div>

                        </form>
                    </div>
                </div>

            </div>


            <div class="col-md-3 ml-auto">
                <div class="mb-5">
                    <h3 class="h5 text-black mb-3">Search</h3>
                    <form action="#" method="post">
                        <div class="form-group d-flex">
                            <input type="text" class="form-control" placeholder="Search keyword and hit enter...">
                        </div>
                    </form>
                </div>

                <div class="mb-5">
                    <h3 class="h5 text-black mb-3">Popular Posts</h3>
                    <ul class="list-unstyled">
                        <li class="mb-2"><a href="#">Lorem ipsum dolor sit amet</a></li>
                        <li class="mb-2"><a href="#">Quaerat rerum voluptatibus veritatis</a></li>
                        <li class="mb-2"><a href="#">Maiores sapiente veritatis reprehenderit</a></li>
                        <li class="mb-2"><a href="#">Natus eligendi nobis</a></li>
                    </ul>
                </div>

                <div class="mb-5">
                    <h3 class="h5 text-black mb-3">Recent Comments</h3>
                    <ul class="list-unstyled">
                        <li class="mb-2"><a href="#">Joefrey</a> <em>in</em> <a href="#">Lorem ipsum dolor sit amet</a></li>
                        <li class="mb-2"><a href="#">Joefrey</a> <em>in</em> <a href="#">Quaerat rerum voluptatibus veritatis</a></li>
                        <li class="mb-2"><a href="#">Joefrey</a> <em>in</em> <a href="#">Maiores sapiente veritatis reprehenderit</a></li>
                        <li class="mb-2"><a href="#">Joefrey</a> <em>in</em> <a href="#">Natus eligendi nobis</a></li>
                    </ul>
                </div>

            </div>

        </div>
    </div>
</div>

<?php include('lfooter.php'); ?>
